import { PokedexConfiguration } from "./models";
import { redBlue } from "./redBlue";

export const goldSilver: PokedexConfiguration = {
  configName: "gold",
  title: "Pokémon Gold & Silver",
  spritesFolderUrl:
    "https://pkdex.blob.core.windows.net/pkdex-assets/gold-silver/",
  attacksUrl:
    "https://pkdex.blob.core.windows.net/pkdex-assets/data/gen2/attacks.json",
  pokemonDataFolderUrl:
    "https://pkdex.blob.core.windows.net/pkdex-assets/data/gen2/pokemon/",
  entries: {
    ...redBlue.entries,
    chikorita: { name: "Chikorita", pokedexNumber: 152, spriteUrl: "152.png" },
    bayleef: { name: "Bayleef", pokedexNumber: 153, spriteUrl: "153.png" },
    meganium: { name: "Meganium", pokedexNumber: 154, spriteUrl: "154.png" },
    cyndaquil: { name: "Cyndaquil", pokedexNumber: 155, spriteUrl: "155.png" },
    quilava: { name: "Quilava", pokedexNumber: 156, spriteUrl: "156.png" },
    typhlosion: {
      name: "Typhlosion",
      pokedexNumber: 157,
      spriteUrl: "157.png",
    },
    totodile: {
      name: "Totodile",
      pokedexNumber: 158,
      spriteUrl: "158.png",
    },
    croconaw: {
      name: "Croconaw",
      pokedexNumber: 159,
      spriteUrl: "159.png",
    },
    feraligatr: {
      name: "Feraligatr",
      pokedexNumber: 160,
      spriteUrl: "160.png",
    },
    sentret: {
      name: "Sentret",
      pokedexNumber: 161,
      spriteUrl: "161.png",
    },
    furret: {
      name: "Furret",
      pokedexNumber: 162,
      spriteUrl: "162.png",
    },
    hoothoot: {
      name: "Hoothoot",
      pokedexNumber: 163,
      spriteUrl: "163.png",
    },
    noctowl: {
      name: "Hoothoot",
      pokedexNumber: 164,
      spriteUrl: "164.png",
    },
    ledyba: {
      name: "Ledyba",
      pokedexNumber: 165,
      spriteUrl: "165.png",
    },
    ledian: {
      name: "Ledian",
      pokedexNumber: 166,
      spriteUrl: "166.png",
    },
    spinarak: {
      name: "Spinarak",
      pokedexNumber: 167,
      spriteUrl: "167.png",
    },
    ariados: {
      name: "Ariados",
      pokedexNumber: 168,
      spriteUrl: "168.png",
    },
    crobat: {
      name: "Crobat",
      pokedexNumber: 169,
      spriteUrl: "169.png",
    },
    chinchou: {
      name: "Chinchou",
      pokedexNumber: 170,
      spriteUrl: "170.png",
    },
    lanturn: {
      name: "Lanturn",
      pokedexNumber: 171,
      spriteUrl: "171.png",
    },
    pichu: {
      name: "Pichu",
      pokedexNumber: 172,
      spriteUrl: "172.png",
    },
    cleffa: {
      name: "Cleffa",
      pokedexNumber: 173,
      spriteUrl: "173.png",
    },
    igglybuff: {
      name: "Igglybuff",
      pokedexNumber: 174,
      spriteUrl: "174.png",
    },
    togepi: {
      name: "Togepi",
      pokedexNumber: 175,
      spriteUrl: "175.png",
    },
    togetic: {
      name: "Togetic",
      pokedexNumber: 176,
      spriteUrl: "176.png",
    },
    natu: {
      name: "Natu",
      pokedexNumber: 177,
      spriteUrl: "177.png",
    },
    xatu: {
      name: "Xatu",
      pokedexNumber: 178,
      spriteUrl: "178.png",
    },
    mareep: {
      name: "Mareep",
      pokedexNumber: 179,
      spriteUrl: "179.png",
    },
    flaaffy: {
      name: "Flaaffy",
      pokedexNumber: 180,
      spriteUrl: "180.png",
    },
    ampharos: {
      name: "Ampharos",
      pokedexNumber: 181,
      spriteUrl: "181.png",
    },
    bellossom: {
      name: "Bellossom",
      pokedexNumber: 182,
      spriteUrl: "182.png",
    },
    marill: {
      name: "Marill",
      pokedexNumber: 183,
      spriteUrl: "183.png",
    },
    azumarill: {
      name: "Azumarill",
      pokedexNumber: 184,
      spriteUrl: "184.png",
    },
    sudowoodo: {
      name: "Sudowoodo",
      pokedexNumber: 185,
      spriteUrl: "185.png",
    },
    politoed: {
      name: "Politoed",
      pokedexNumber: 186,
      spriteUrl: "186.png",
    },
    hoppip: {
      name: "Hoppip",
      pokedexNumber: 187,
      spriteUrl: "187.png",
    },
    skiploom: {
      name: "Skiploom",
      pokedexNumber: 188,
      spriteUrl: "188.png",
    },
    jumpluff: {
      name: "Jumpluff",
      pokedexNumber: 189,
      spriteUrl: "189.png",
    },
    aipom: {
      name: "Aipom",
      pokedexNumber: 190,
      spriteUrl: "190.png",
    },
    sunkern: {
      name: "Sunkern",
      pokedexNumber: 191,
      spriteUrl: "191.png",
    },
    sunflora: {
      name: "Sunflora",
      pokedexNumber: 192,
      spriteUrl: "192.png",
    },
    yanma: {
      name: "Yanma",
      pokedexNumber: 193,
      spriteUrl: "193.png",
    },
    wooper: {
      name: "Wooper",
      pokedexNumber: 194,
      spriteUrl: "194.png",
    },
    quagsire: {
      name: "Quagsire",
      pokedexNumber: 195,
      spriteUrl: "195.png",
    },
    espeon: {
      name: "Espeon",
      pokedexNumber: 196,
      spriteUrl: "196.png",
    },
    umbreon: {
      name: "Umbreon",
      pokedexNumber: 197,
      spriteUrl: "197.png",
    },
    murkrow: {
      name: "Murkrow",
      pokedexNumber: 198,
      spriteUrl: "198.png",
    },
    slowking: {
      name: "Slowking",
      pokedexNumber: 199,
      spriteUrl: "199.png",
    },
    misdreavus: {
      name: "Misdreavus",
      pokedexNumber: 200,
      spriteUrl: "200.png",
    },
    unown: {
      name: "Unown",
      pokedexNumber: 201,
      spriteUrl: "201.png",
    },
    wobbuffet: {
      name: "Wobbuffet",
      pokedexNumber: 202,
      spriteUrl: "202.png",
    },
    girafarig: {
      name: "Girafarig",
      pokedexNumber: 203,
      spriteUrl: "203.png",
    },
    pineco: {
      name: "Pineco",
      pokedexNumber: 204,
      spriteUrl: "204.png",
    },
    forretress: {
      name: "Forretress",
      pokedexNumber: 205,
      spriteUrl: "205.png",
    },
    dunsparce: {
      name: "Dunsparce",
      pokedexNumber: 206,
      spriteUrl: "206.png",
    },
    gligar: {
      name: "Gligar",
      pokedexNumber: 207,
      spriteUrl: "207.png",
    },
    steelix: {
      name: "Steelix",
      pokedexNumber: 208,
      spriteUrl: "208.png",
    },
    snubbull: {
      name: "Snubbull",
      pokedexNumber: 209,
      spriteUrl: "209.png",
    },
    granbull: {
      name: "Granbull",
      pokedexNumber: 210,
      spriteUrl: "210.png",
    },
    qwilfish: {
      name: "Qwilfish",
      pokedexNumber: 211,
      spriteUrl: "211.png",
    },
    scizor: {
      name: "Scizor",
      pokedexNumber: 212,
      spriteUrl: "212.png",
    },
    shuckle: {
      name: "Shuckle",
      pokedexNumber: 213,
      spriteUrl: "213.png",
    },
    heracross: {
      name: "Heracross",
      pokedexNumber: 214,
      spriteUrl: "214.png",
    },
    sneasel: {
      name: "Sneasel",
      pokedexNumber: 215,
      spriteUrl: "215.png",
    },
    teddiursa: {
      name: "Teddiursa",
      pokedexNumber: 216,
      spriteUrl: "216.png",
    },
    ursaring: {
      name: "Ursaring",
      pokedexNumber: 217,
      spriteUrl: "217.png",
    },
    slugma: {
      name: "Slugma",
      pokedexNumber: 218,
      spriteUrl: "218.png",
    },
    magcargo: {
      name: "Magcargo",
      pokedexNumber: 219,
      spriteUrl: "219.png",
    },
    swinub: {
      name: "Swinub",
      pokedexNumber: 220,
      spriteUrl: "220.png",
    },
    piloswine: {
      name: "Piloswine",
      pokedexNumber: 221,
      spriteUrl: "221.png",
    },
    corsola: {
      name: "Corsola",
      pokedexNumber: 222,
      spriteUrl: "222.png",
    },
    remoraid: {
      name: "Remoraid",
      pokedexNumber: 223,
      spriteUrl: "223.png",
    },
    octillery: {
      name: "Octillery",
      pokedexNumber: 224,
      spriteUrl: "224.png",
    },
    delibird: {
      name: "Delibird",
      pokedexNumber: 225,
      spriteUrl: "225.png",
    },
    mantine: {
      name: "Mantine",
      pokedexNumber: 226,
      spriteUrl: "226.png",
    },
    skarmory: {
      name: "Skarmory",
      pokedexNumber: 227,
      spriteUrl: "227.png",
    },
    houndour: {
      name: "Houndour",
      pokedexNumber: 228,
      spriteUrl: "228.png",
    },
    houndoom: {
      name: "Houndoom",
      pokedexNumber: 229,
      spriteUrl: "229.png",
    },
    kingdra: {
      name: "Kingdra",
      pokedexNumber: 230,
      spriteUrl: "230.png",
    },
    phanpy: {
      name: "Phanpy",
      pokedexNumber: 231,
      spriteUrl: "231.png",
    },
    donphan: {
      name: "Donphan",
      pokedexNumber: 232,
      spriteUrl: "232.png",
    },
    porygon2: {
      name: "Porygon2",
      pokedexNumber: 233,
      spriteUrl: "233.png",
    },
    stantler: {
      name: "Stantler",
      pokedexNumber: 234,
      spriteUrl: "234.png",
    },
    smeargle: {
      name: "Smeargle",
      pokedexNumber: 235,
      spriteUrl: "235.png",
    },
    tyrogue: {
      name: "Tyrogue",
      pokedexNumber: 236,
      spriteUrl: "236.png",
    },
    hitmontop: {
      name: "Hitmontop",
      pokedexNumber: 237,
      spriteUrl: "237.png",
    },
    smoochum: {
      name: "Smoochum",
      pokedexNumber: 238,
      spriteUrl: "238.png",
    },
    elekid: {
      name: "Elekid",
      pokedexNumber: 239,
      spriteUrl: "239.png",
    },
    magby: {
      name: "Magby",
      pokedexNumber: 240,
      spriteUrl: "240.png",
    },
    miltank: {
      name: "Miltank",
      pokedexNumber: 241,
      spriteUrl: "241.png",
    },
    blissey: {
      name: "Blissey",
      pokedexNumber: 242,
      spriteUrl: "242.png",
    },
    raikou: {
      name: "Raikou",
      pokedexNumber: 243,
      spriteUrl: "243.png",
    },
    entei: {
      name: "Entei",
      pokedexNumber: 244,
      spriteUrl: "244.png",
    },
    suicune: {
      name: "Suicune",
      pokedexNumber: 245,
      spriteUrl: "245.png",
    },
    larvitar: {
      name: "Larvitar",
      pokedexNumber: 246,
      spriteUrl: "246.png",
    },
    pupitar: {
      name: "Pupitar",
      pokedexNumber: 247,
      spriteUrl: "247.png",
    },
    tyranitar: {
      name: "Tyranitar",
      pokedexNumber: 248,
      spriteUrl: "248.png",
    },
    lugia: {
      name: "Lugia",
      pokedexNumber: 249,
      spriteUrl: "249.png",
    },
    "ho-oh": {
      name: "Ho-Oh",
      pokedexNumber: 250,
      spriteUrl: "250.png",
    },
    celebi: {
      name: "Celebi",
      pokedexNumber: 251,
      spriteUrl: "251.png",
    },
  },
  indexByNumber: {
    ...redBlue.indexByNumber,
    152: "chikorita",
    153: "bayleef",
    154: "meganium",
    155: "cyndaquil",
    156: "quilava",
    157: "typhlosion",
    158: "totodile",
    159: "croconaw",
    160: "feraligatr",
    161: "sentret",
    162: "furret",
    163: "hoothoot",
    164: "noctowl",
    165: "ledyba",
    166: "ledian",
    167: "spinarak",
    168: "ariados",
    169: "crobat",
    170: "chinchou",
    171: "lanturn",
    172: "pichu",
    173: "cleffa",
    174: "igglybuff",
    175: "togepi",
    176: "togetic",
    177: "natu",
    178: "xatu",
    179: "mareep",
    180: "flaaffy",
    181: "ampharos",
    182: "bellossom",
    183: "marill",
    184: "azumarill",
    185: "sudowoodo",
    186: "politoed",
    187: "hoppip",
    188: "skiploom",
    189: "jumpluff",
    190: "aipom",
    191: "sunkern",
    192: "sunflora",
    193: "yanma",
    194: "wooper",
    195: "quagsire",
    196: "espeon",
    197: "umbreon",
    198: "murkrow",
    199: "slowking",
    200: "misdreavus",
    201: "unown",
    202: "wobbuffet",
    203: "girafarig",
    204: "pineco",
    205: "forretress",
    206: "dunsparce",
    207: "gligar",
    208: "steelix",
    209: "snubbull",
    210: "granbull",
    211: "qwilfish",
    212: "scizor",
    213: "shuckle",
    214: "heracross",
    215: "sneasel",
    216: "teddiursa",
    217: "ursaring",
    218: "slugma",
    219: "magcargo",
    220: "swinub",
    221: "piloswine",
    222: "corsola",
    223: "remoraid",
    224: "octillery",
    225: "delibird",
    226: "mantine",
    227: "skarmory",
    228: "houndour",
    229: "houndoom",
    230: "kingdra",
    231: "phanpy",
    232: "donphan",
    233: "porygon2",
    234: "stantler",
    235: "smeargle",
    236: "tyrogue",
    237: "hitmontop",
    238: "smoochum",
    239: "elekid",
    240: "magby",
    241: "miltank",
    242: "blissey",
    243: "raikou",
    244: "entei",
    245: "suicune",
    246: "larvitar",
    247: "pupitar",
    248: "tyranitar",
    249: "lugia",
    250: "ho-oh",
    251: "celebi",
  },
};
