import { PokedexConfiguration } from "./models";

export const redBlue: PokedexConfiguration = {
  configName: "red-blue",
  spritesFolderUrl: "/assets/sprites/red-blue/",
  attacksUrl: "/assets/data/gen1/attacks.json",
  pokemonDataFolderUrl: "/assets/data/gen1/pokemon/",
  entries: {
    bulbasaur: { name: "Bulbasaur", pokedexNumber: 1, spriteUrl: "1.png" },
    ivysaur: { name: "Ivysaur", pokedexNumber: 2, spriteUrl: "2.png" },
    venusaur: { name: "Venusaur", pokedexNumber: 3, spriteUrl: "3.png" },
    charmander: { name: "Charmander", pokedexNumber: 4, spriteUrl: "4.png" },
    charmeleon: { name: "Charmeleon", pokedexNumber: 5, spriteUrl: "5.png" },
    charizard: { name: "Charizard", pokedexNumber: 6, spriteUrl: "6.png" },
    squirtle: { name: "Squirtle", pokedexNumber: 7, spriteUrl: "7.png" },
    wartortle: { name: "Wartortle", pokedexNumber: 8, spriteUrl: "8.png" },
    blastoise: { name: "Blastoise", pokedexNumber: 9, spriteUrl: "9.png" },
    caterpie: { name: "Caterpie", pokedexNumber: 10, spriteUrl: "10.png" },
    metapod: { name: "Metapod", pokedexNumber: 11, spriteUrl: "11.png" },
    butterfree: { name: "Butterfree", pokedexNumber: 12, spriteUrl: "12.png" },
    weedle: { name: "Weedle", pokedexNumber: 13, spriteUrl: "13.png" },
    kakuna: { name: "Kakuna", pokedexNumber: 14, spriteUrl: "14.png" },
    beedrill: { name: "Beedrill", pokedexNumber: 15, spriteUrl: "15.png" },
    pidgey: { name: "Pidgey", pokedexNumber: 16, spriteUrl: "16.png" },
    pidgeotto: { name: "Pidgeotto", pokedexNumber: 17, spriteUrl: "17.png" },
    pidgeot: { name: "Pidgeot", pokedexNumber: 18, spriteUrl: "18.png" },
    rattata: { name: "Rattata", pokedexNumber: 19, spriteUrl: "19.png" },
    raticate: { name: "Raticate", pokedexNumber: 20, spriteUrl: "20.png" },
    spearow: { name: "Spearow", pokedexNumber: 21, spriteUrl: "21.png" },
    fearow: { name: "Fearow", pokedexNumber: 22, spriteUrl: "22.png" },
    ekans: { name: "Ekans", pokedexNumber: 23, spriteUrl: "23.png" },
    arbok: { name: "Arbok", pokedexNumber: 24, spriteUrl: "24.png" },
    pikachu: { name: "Pikachu", pokedexNumber: 25, spriteUrl: "25.png" },
    raichu: { name: "Raichu", pokedexNumber: 26, spriteUrl: "26.png" },
    sandshrew: { name: "Sandshrew", pokedexNumber: 27, spriteUrl: "27.png" },
    sandslash: { name: "Sandslash", pokedexNumber: 28, spriteUrl: "28.png" },
    nidoranf: { name: "Nidoran ♀", pokedexNumber: 29, spriteUrl: "29.png" },
    nidorina: { name: "Nidorina", pokedexNumber: 30, spriteUrl: "30.png" },
    nidoqueen: { name: "Nidoqueen", pokedexNumber: 31, spriteUrl: "31.png" },
    nidoranm: { name: "Nidoran ♂", pokedexNumber: 32, spriteUrl: "32.png" },
    nidorino: { name: "Nidorino", pokedexNumber: 33, spriteUrl: "33.png" },
    nidoking: { name: "Nidoking", pokedexNumber: 34, spriteUrl: "34.png" },
    clefairy: { name: "Clefairy", pokedexNumber: 35, spriteUrl: "35.png" },
    clefable: { name: "Clefable", pokedexNumber: 36, spriteUrl: "36.png" },
    vulpix: { name: "Vulpix", pokedexNumber: 37, spriteUrl: "37.png" },
    ninetales: { name: "Ninetales", pokedexNumber: 38, spriteUrl: "38.png" },
    jigglypuff: { name: "Jigglypuff", pokedexNumber: 39, spriteUrl: "39.png" },
    wigglytuff: { name: "Wigglytuff", pokedexNumber: 40, spriteUrl: "40.png" },
    zubat: { name: "Zubat", pokedexNumber: 41, spriteUrl: "41.png" },
    golbat: { name: "Golbat", pokedexNumber: 42, spriteUrl: "42.png" },
    oddish: { name: "Oddish", pokedexNumber: 43, spriteUrl: "43.png" },
    gloom: { name: "Gloom", pokedexNumber: 44, spriteUrl: "44.png" },
    vileplume: { name: "Vileplume", pokedexNumber: 45, spriteUrl: "45.png" },
    paras: { name: "Paras", pokedexNumber: 46, spriteUrl: "46.png" },
    parasect: { name: "Parasect", pokedexNumber: 47, spriteUrl: "47.png" },
    venonat: { name: "Venonat", pokedexNumber: 48, spriteUrl: "48.png" },
    venomoth: { name: "Venomoth", pokedexNumber: 49, spriteUrl: "49.png" },
    diglett: { name: "Diglett", pokedexNumber: 50, spriteUrl: "50.png" },
    dugtrio: { name: "Dugtrio", pokedexNumber: 51, spriteUrl: "51.png" },
    meowth: { name: "Meowth", pokedexNumber: 52, spriteUrl: "52.png" },
    persian: { name: "Persian", pokedexNumber: 53, spriteUrl: "53.png" },
    psyduck: { name: "Psyduck", pokedexNumber: 54, spriteUrl: "54.png" },
    golduck: { name: "Golduck", pokedexNumber: 55, spriteUrl: "55.png" },
    mankey: { name: "Mankey", pokedexNumber: 56, spriteUrl: "56.png" },
    primeape: { name: "Primeape", pokedexNumber: 57, spriteUrl: "57.png" },
    growlithe: { name: "Growlithe", pokedexNumber: 58, spriteUrl: "58.png" },
    arcanine: { name: "Arcanine", pokedexNumber: 59, spriteUrl: "59.png" },
    poliwag: { name: "Poliwag", pokedexNumber: 60, spriteUrl: "60.png" },
    poliwhirl: { name: "Poliwhirl", pokedexNumber: 61, spriteUrl: "61.png" },
    poliwrath: { name: "Poliwrath", pokedexNumber: 62, spriteUrl: "62.png" },
    abra: { name: "Abra", pokedexNumber: 63, spriteUrl: "63.png" },
    kadabra: { name: "Kadabra", pokedexNumber: 64, spriteUrl: "64.png" },
    alakazam: { name: "Alakazam", pokedexNumber: 65, spriteUrl: "65.png" },
    machop: { name: "Machop", pokedexNumber: 66, spriteUrl: "66.png" },
    machoke: { name: "Machoke", pokedexNumber: 67, spriteUrl: "67.png" },
    machamp: { name: "Machamp", pokedexNumber: 68, spriteUrl: "68.png" },
    bellsprout: { name: "Bellsprout", pokedexNumber: 69, spriteUrl: "69.png" },
    weepinbell: { name: "Weepinbell", pokedexNumber: 70, spriteUrl: "70.png" },
    victreebel: { name: "Victreebel", pokedexNumber: 71, spriteUrl: "71.png" },
    tentacool: { name: "Tentacool", pokedexNumber: 72, spriteUrl: "72.png" },
    tentacruel: { name: "Tentacruel", pokedexNumber: 73, spriteUrl: "73.png" },
    geodude: { name: "Geodude", pokedexNumber: 74, spriteUrl: "74.png" },
    graveler: { name: "Graveler", pokedexNumber: 75, spriteUrl: "75.png" },
    golem: { name: "Golem", pokedexNumber: 76, spriteUrl: "76.png" },
    ponyta: { name: "Ponyta", pokedexNumber: 77, spriteUrl: "77.png" },
    rapidash: { name: "Rapidash", pokedexNumber: 78, spriteUrl: "78.png" },
    slowpoke: { name: "Slowpoke", pokedexNumber: 79, spriteUrl: "79.png" },
    slowbro: { name: "Slowbro", pokedexNumber: 80, spriteUrl: "80.png" },
    magnemite: { name: "Magnemite", pokedexNumber: 81, spriteUrl: "81.png" },
    magneton: { name: "Magneton", pokedexNumber: 82, spriteUrl: "82.png" },
    farfetchd: {
      name: "Farfetch'd",
      pokedexNumber: 83,
      spriteUrl: "83.png",
    },
    doduo: { name: "Doduo", pokedexNumber: 84, spriteUrl: "84.png" },
    dodrio: { name: "Dodrio", pokedexNumber: 85, spriteUrl: "85.png" },
    seel: { name: "Seel", pokedexNumber: 86, spriteUrl: "86.png" },
    dewgong: { name: "Dewgong", pokedexNumber: 87, spriteUrl: "87.png" },
    grimer: { name: "Grimer", pokedexNumber: 88, spriteUrl: "88.png" },
    muk: { name: "Muk", pokedexNumber: 89, spriteUrl: "89.png" },
    shellder: { name: "Shellder", pokedexNumber: 90, spriteUrl: "90.png" },
    cloyster: { name: "Cloyster", pokedexNumber: 91, spriteUrl: "91.png" },
    gastly: { name: "Gastly", pokedexNumber: 92, spriteUrl: "92.png" },
    haunter: { name: "Haunter", pokedexNumber: 93, spriteUrl: "93.png" },
    gengar: { name: "Gengar", pokedexNumber: 94, spriteUrl: "94.png" },
    onix: { name: "Onix", pokedexNumber: 95, spriteUrl: "95.png" },
    drowzee: { name: "Drowzee", pokedexNumber: 96, spriteUrl: "96.png" },
    hypno: { name: "Hypno", pokedexNumber: 97, spriteUrl: "97.png" },
    krabby: { name: "Krabby", pokedexNumber: 98, spriteUrl: "98.png" },
    kingler: { name: "Kingler", pokedexNumber: 99, spriteUrl: "99.png" },
    voltorb: { name: "Voltorb", pokedexNumber: 100, spriteUrl: "100.png" },
    electrode: { name: "Electrode", pokedexNumber: 101, spriteUrl: "101.png" },
    exeggcute: { name: "Exeggcute", pokedexNumber: 102, spriteUrl: "102.png" },
    exeggutor: { name: "Exeggutor", pokedexNumber: 103, spriteUrl: "103.png" },
    cubone: { name: "Cubone", pokedexNumber: 104, spriteUrl: "104.png" },
    marowak: { name: "Marowak", pokedexNumber: 105, spriteUrl: "105.png" },
    hitmonlee: { name: "Hitmonlee", pokedexNumber: 106, spriteUrl: "106.png" },
    hitmonchan: {
      name: "Hitmonchan",
      pokedexNumber: 107,
      spriteUrl: "107.png",
    },
    lickitung: { name: "Lickitung", pokedexNumber: 108, spriteUrl: "108.png" },
    koffing: { name: "Koffing", pokedexNumber: 109, spriteUrl: "109.png" },
    weezing: { name: "Weezing", pokedexNumber: 110, spriteUrl: "110.png" },
    rhyhorn: { name: "Rhyhorn", pokedexNumber: 111, spriteUrl: "111.png" },
    rhydon: { name: "Rhydon", pokedexNumber: 112, spriteUrl: "112.png" },
    chansey: { name: "Chansey", pokedexNumber: 113, spriteUrl: "113.png" },
    tangela: { name: "Tangela", pokedexNumber: 114, spriteUrl: "114.png" },
    kangaskhan: {
      name: "Kangaskhan",
      pokedexNumber: 115,
      spriteUrl: "115.png",
    },
    horsea: { name: "Horsea", pokedexNumber: 116, spriteUrl: "116.png" },
    seadra: { name: "Seadra", pokedexNumber: 117, spriteUrl: "117.png" },
    goldeen: { name: "Goldeen", pokedexNumber: 118, spriteUrl: "118.png" },
    seaking: { name: "Seaking", pokedexNumber: 119, spriteUrl: "119.png" },
    staryu: { name: "Staryu", pokedexNumber: 120, spriteUrl: "120.png" },
    starmie: { name: "Starmie", pokedexNumber: 121, spriteUrl: "121.png" },
    mrmime: { name: "Mr. Mime", pokedexNumber: 122, spriteUrl: "122.png" },
    scyther: { name: "Scyther", pokedexNumber: 123, spriteUrl: "123.png" },
    jynx: { name: "Jynx", pokedexNumber: 124, spriteUrl: "124.png" },
    electabuzz: {
      name: "Electabuzz",
      pokedexNumber: 125,
      spriteUrl: "125.png",
    },
    magmar: { name: "Magmar", pokedexNumber: 126, spriteUrl: "126.png" },
    pinsir: { name: "Pinsir", pokedexNumber: 127, spriteUrl: "127.png" },
    tauros: { name: "Tauros", pokedexNumber: 128, spriteUrl: "128.png" },
    magikarp: { name: "Magikarp", pokedexNumber: 129, spriteUrl: "129.png" },
    gyarados: { name: "Gyarados", pokedexNumber: 130, spriteUrl: "130.png" },
    lapras: { name: "Lapras", pokedexNumber: 131, spriteUrl: "131.png" },
    ditto: { name: "Ditto", pokedexNumber: 132, spriteUrl: "132.png" },
    eevee: { name: "Eevee", pokedexNumber: 133, spriteUrl: "133.png" },
    vaporeon: { name: "Vaporeon", pokedexNumber: 134, spriteUrl: "134.png" },
    jolteon: { name: "Jolteon", pokedexNumber: 135, spriteUrl: "135.png" },
    flareon: { name: "Flareon", pokedexNumber: 136, spriteUrl: "136.png" },
    porygon: { name: "Porygon", pokedexNumber: 137, spriteUrl: "137.png" },
    omanyte: { name: "Omanyte", pokedexNumber: 138, spriteUrl: "138.png" },
    omastar: { name: "Omastar", pokedexNumber: 139, spriteUrl: "139.png" },
    kabuto: { name: "Kabuto", pokedexNumber: 140, spriteUrl: "140.png" },
    kabutops: { name: "Kabutops", pokedexNumber: 141, spriteUrl: "141.png" },
    aerodactyl: {
      name: "Aerodactyl",
      pokedexNumber: 142,
      spriteUrl: "142.png",
    },
    snorlax: { name: "Snorlax", pokedexNumber: 143, spriteUrl: "143.png" },
    articuno: { name: "Articuno", pokedexNumber: 144, spriteUrl: "144.png" },
    zapdos: { name: "Zapdos", pokedexNumber: 145, spriteUrl: "145.png" },
    moltres: { name: "Moltres", pokedexNumber: 146, spriteUrl: "146.png" },
    dratini: { name: "Dratini", pokedexNumber: 147, spriteUrl: "147.png" },
    dragonair: { name: "Dragonair", pokedexNumber: 148, spriteUrl: "148.png" },
    dragonite: { name: "Dragonite", pokedexNumber: 149, spriteUrl: "149.png" },
    mewtwo: { name: "Mewtwo", pokedexNumber: 150, spriteUrl: "150.png" },
    mew: { name: "Mew", pokedexNumber: 151, spriteUrl: "151.png" },
  },
};
