import { PokedexConfiguration } from "./model";

export const redBlue: PokedexConfiguration = {
  configName: "red-blue",
  spritesFolderUrl: "/assets/sprites/red-blue/",
  entries: {
    Bulbasaur: { name: "Bulbasaur", pokedexNumber: 1, spriteUrl: "1.png" },
    Ivysaur: { name: "Ivysaur", pokedexNumber: 2, spriteUrl: "2.png" },
    Venusaur: { name: "Venusaur", pokedexNumber: 3, spriteUrl: "3.png" },
    Charmander: { name: "Charmander", pokedexNumber: 4, spriteUrl: "4.png" },
    Charmeleon: { name: "Charmeleon", pokedexNumber: 5, spriteUrl: "5.png" },
    Charizard: { name: "Charizard", pokedexNumber: 6, spriteUrl: "6.png" },
    Squirtle: { name: "Squirtle", pokedexNumber: 7, spriteUrl: "7.png" },
    Wartortle: { name: "Wartortle", pokedexNumber: 8, spriteUrl: "8.png" },
    Blastoise: { name: "Blastoise", pokedexNumber: 9, spriteUrl: "9.png" },
    Caterpie: { name: "Caterpie", pokedexNumber: 10, spriteUrl: "10.png" },
    Metapod: { name: "Metapod", pokedexNumber: 11, spriteUrl: "11.png" },
    Butterfree: { name: "Butterfree", pokedexNumber: 12, spriteUrl: "12.png" },
    Weedle: { name: "Weedle", pokedexNumber: 13, spriteUrl: "13.png" },
    Kakuna: { name: "Kakuna", pokedexNumber: 14, spriteUrl: "14.png" },
    Beedrill: { name: "Beedrill", pokedexNumber: 15, spriteUrl: "15.png" },
    Pidgey: { name: "Pidgey", pokedexNumber: 16, spriteUrl: "16.png" },
    Pidgeotto: { name: "Pidgeotto", pokedexNumber: 17, spriteUrl: "17.png" },
    Pidgeot: { name: "Pidgeot", pokedexNumber: 18, spriteUrl: "18.png" },
    Rattata: { name: "Rattata", pokedexNumber: 19, spriteUrl: "19.png" },
    Raticate: { name: "Raticate", pokedexNumber: 20, spriteUrl: "20.png" },
    Spearow: { name: "Spearow", pokedexNumber: 21, spriteUrl: "21.png" },
    Fearow: { name: "Fearow", pokedexNumber: 22, spriteUrl: "22.png" },
    Ekans: { name: "Ekans", pokedexNumber: 23, spriteUrl: "23.png" },
    Arbok: { name: "Arbok", pokedexNumber: 24, spriteUrl: "24.png" },
    Pikachu: { name: "Pikachu", pokedexNumber: 25, spriteUrl: "25.png" },
    Raichu: { name: "Raichu", pokedexNumber: 26, spriteUrl: "26.png" },
    Sandshrew: { name: "Sandshrew", pokedexNumber: 27, spriteUrl: "27.png" },
    Sandslash: { name: "Sandslash", pokedexNumber: 28, spriteUrl: "28.png" },
    "Nidoran ♀": { name: "Nidoran ♀", pokedexNumber: 29, spriteUrl: "29.png" },
    Nidorina: { name: "Nidorina", pokedexNumber: 30, spriteUrl: "30.png" },
    Nidoqueen: { name: "Nidoqueen", pokedexNumber: 31, spriteUrl: "31.png" },
    "Nidoran ♂": { name: "Nidoran ♂", pokedexNumber: 32, spriteUrl: "32.png" },
    Nidorino: { name: "Nidorino", pokedexNumber: 33, spriteUrl: "33.png" },
    Nidoking: { name: "Nidoking", pokedexNumber: 34, spriteUrl: "34.png" },
    Clefairy: { name: "Clefairy", pokedexNumber: 35, spriteUrl: "35.png" },
    Clefable: { name: "Clefable", pokedexNumber: 36, spriteUrl: "36.png" },
    Vulpix: { name: "Vulpix", pokedexNumber: 37, spriteUrl: "37.png" },
    Ninetales: { name: "Ninetales", pokedexNumber: 38, spriteUrl: "38.png" },
    Jigglypuff: { name: "Jigglypuff", pokedexNumber: 39, spriteUrl: "39.png" },
    Wigglytuff: { name: "Wigglytuff", pokedexNumber: 40, spriteUrl: "40.png" },
    Zubat: { name: "Zubat", pokedexNumber: 41, spriteUrl: "41.png" },
    Golbat: { name: "Golbat", pokedexNumber: 42, spriteUrl: "42.png" },
    Oddish: { name: "Oddish", pokedexNumber: 43, spriteUrl: "43.png" },
    Gloom: { name: "Gloom", pokedexNumber: 44, spriteUrl: "44.png" },
    Vileplume: { name: "Vileplume", pokedexNumber: 45, spriteUrl: "45.png" },
    Paras: { name: "Paras", pokedexNumber: 46, spriteUrl: "46.png" },
    Parasect: { name: "Parasect", pokedexNumber: 47, spriteUrl: "47.png" },
    Venonat: { name: "Venonat", pokedexNumber: 48, spriteUrl: "48.png" },
    Venomoth: { name: "Venomoth", pokedexNumber: 49, spriteUrl: "49.png" },
    Diglett: { name: "Diglett", pokedexNumber: 50, spriteUrl: "50.png" },
    Dugtrio: { name: "Dugtrio", pokedexNumber: 51, spriteUrl: "51.png" },
    Meowth: { name: "Meowth", pokedexNumber: 52, spriteUrl: "52.png" },
    Persian: { name: "Persian", pokedexNumber: 53, spriteUrl: "53.png" },
    Psyduck: { name: "Psyduck", pokedexNumber: 54, spriteUrl: "54.png" },
    Golduck: { name: "Golduck", pokedexNumber: 55, spriteUrl: "55.png" },
    Mankey: { name: "Mankey", pokedexNumber: 56, spriteUrl: "56.png" },
    Primeape: { name: "Primeape", pokedexNumber: 57, spriteUrl: "57.png" },
    Growlithe: { name: "Growlithe", pokedexNumber: 58, spriteUrl: "58.png" },
    Arcanine: { name: "Arcanine", pokedexNumber: 59, spriteUrl: "59.png" },
    Poliwag: { name: "Poliwag", pokedexNumber: 60, spriteUrl: "60.png" },
    Poliwhirl: { name: "Poliwhirl", pokedexNumber: 61, spriteUrl: "61.png" },
    Poliwrath: { name: "Poliwrath", pokedexNumber: 62, spriteUrl: "62.png" },
    Abra: { name: "Abra", pokedexNumber: 63, spriteUrl: "63.png" },
    Kadabra: { name: "Kadabra", pokedexNumber: 64, spriteUrl: "64.png" },
    Alakazam: { name: "Alakazam", pokedexNumber: 65, spriteUrl: "65.png" },
    Machop: { name: "Machop", pokedexNumber: 66, spriteUrl: "66.png" },
    Machoke: { name: "Machoke", pokedexNumber: 67, spriteUrl: "67.png" },
    Machamp: { name: "Machamp", pokedexNumber: 68, spriteUrl: "68.png" },
    Bellsprout: { name: "Bellsprout", pokedexNumber: 69, spriteUrl: "69.png" },
    Weepinbell: { name: "Weepinbell", pokedexNumber: 70, spriteUrl: "70.png" },
    Victreebel: { name: "Victreebel", pokedexNumber: 71, spriteUrl: "71.png" },
    Tentacool: { name: "Tentacool", pokedexNumber: 72, spriteUrl: "72.png" },
    Tentacruel: { name: "Tentacruel", pokedexNumber: 73, spriteUrl: "73.png" },
    Geodude: { name: "Geodude", pokedexNumber: 74, spriteUrl: "74.png" },
    Graveler: { name: "Graveler", pokedexNumber: 75, spriteUrl: "75.png" },
    Golem: { name: "Golem", pokedexNumber: 76, spriteUrl: "76.png" },
    Ponyta: { name: "Ponyta", pokedexNumber: 77, spriteUrl: "77.png" },
    Rapidash: { name: "Rapidash", pokedexNumber: 78, spriteUrl: "78.png" },
    Slowpoke: { name: "Slowpoke", pokedexNumber: 79, spriteUrl: "79.png" },
    Slowbro: { name: "Slowbro", pokedexNumber: 80, spriteUrl: "80.png" },
    Magnemite: { name: "Magnemite", pokedexNumber: 81, spriteUrl: "81.png" },
    Magneton: { name: "Magneton", pokedexNumber: 82, spriteUrl: "82.png" },
    "Farfetch'd": {
      name: "Farfetch'd",
      pokedexNumber: 83,
      spriteUrl: "83.png",
    },
    Doduo: { name: "Doduo", pokedexNumber: 84, spriteUrl: "84.png" },
    Dodrio: { name: "Dodrio", pokedexNumber: 85, spriteUrl: "85.png" },
    Seel: { name: "Seel", pokedexNumber: 86, spriteUrl: "86.png" },
    Dewgong: { name: "Dewgong", pokedexNumber: 87, spriteUrl: "87.png" },
    Grimer: { name: "Grimer", pokedexNumber: 88, spriteUrl: "88.png" },
    Muk: { name: "Muk", pokedexNumber: 89, spriteUrl: "89.png" },
    Shellder: { name: "Shellder", pokedexNumber: 90, spriteUrl: "90.png" },
    Cloyster: { name: "Cloyster", pokedexNumber: 91, spriteUrl: "91.png" },
    Gastly: { name: "Gastly", pokedexNumber: 92, spriteUrl: "92.png" },
    Haunter: { name: "Haunter", pokedexNumber: 93, spriteUrl: "93.png" },
    Gengar: { name: "Gengar", pokedexNumber: 94, spriteUrl: "94.png" },
    Onix: { name: "Onix", pokedexNumber: 95, spriteUrl: "95.png" },
    Drowzee: { name: "Drowzee", pokedexNumber: 96, spriteUrl: "96.png" },
    Hypno: { name: "Hypno", pokedexNumber: 97, spriteUrl: "97.png" },
    Krabby: { name: "Krabby", pokedexNumber: 98, spriteUrl: "98.png" },
    Kingler: { name: "Kingler", pokedexNumber: 99, spriteUrl: "99.png" },
    Voltorb: { name: "Voltorb", pokedexNumber: 100, spriteUrl: "100.png" },
    Electrode: { name: "Electrode", pokedexNumber: 101, spriteUrl: "101.png" },
    Exeggcute: { name: "Exeggcute", pokedexNumber: 102, spriteUrl: "102.png" },
    Exeggutor: { name: "Exeggutor", pokedexNumber: 103, spriteUrl: "103.png" },
    Cubone: { name: "Cubone", pokedexNumber: 104, spriteUrl: "104.png" },
    Marowak: { name: "Marowak", pokedexNumber: 105, spriteUrl: "105.png" },
    Hitmonlee: { name: "Hitmonlee", pokedexNumber: 106, spriteUrl: "106.png" },
    Hitmonchan: {
      name: "Hitmonchan",
      pokedexNumber: 107,
      spriteUrl: "107.png",
    },
    Lickitung: { name: "Lickitung", pokedexNumber: 108, spriteUrl: "108.png" },
    Koffing: { name: "Koffing", pokedexNumber: 109, spriteUrl: "109.png" },
    Weezing: { name: "Weezing", pokedexNumber: 110, spriteUrl: "110.png" },
    Rhyhorn: { name: "Rhyhorn", pokedexNumber: 111, spriteUrl: "111.png" },
    Rhydon: { name: "Rhydon", pokedexNumber: 112, spriteUrl: "112.png" },
    Chansey: { name: "Chansey", pokedexNumber: 113, spriteUrl: "113.png" },
    Tangela: { name: "Tangela", pokedexNumber: 114, spriteUrl: "114.png" },
    Kangaskhan: {
      name: "Kangaskhan",
      pokedexNumber: 115,
      spriteUrl: "115.png",
    },
    Horsea: { name: "Horsea", pokedexNumber: 116, spriteUrl: "116.png" },
    Seadra: { name: "Seadra", pokedexNumber: 117, spriteUrl: "117.png" },
    Goldeen: { name: "Goldeen", pokedexNumber: 118, spriteUrl: "118.png" },
    Seaking: { name: "Seaking", pokedexNumber: 119, spriteUrl: "119.png" },
    Staryu: { name: "Staryu", pokedexNumber: 120, spriteUrl: "120.png" },
    Starmie: { name: "Starmie", pokedexNumber: 121, spriteUrl: "121.png" },
    "Mr. Mime": { name: "Mr. Mime", pokedexNumber: 122, spriteUrl: "122.png" },
    Scyther: { name: "Scyther", pokedexNumber: 123, spriteUrl: "123.png" },
    Jynx: { name: "Jynx", pokedexNumber: 124, spriteUrl: "124.png" },
    Electabuzz: {
      name: "Electabuzz",
      pokedexNumber: 125,
      spriteUrl: "125.png",
    },
    Magmar: { name: "Magmar", pokedexNumber: 126, spriteUrl: "126.png" },
    Pinsir: { name: "Pinsir", pokedexNumber: 127, spriteUrl: "127.png" },
    Tauros: { name: "Tauros", pokedexNumber: 128, spriteUrl: "128.png" },
    Magikarp: { name: "Magikarp", pokedexNumber: 129, spriteUrl: "129.png" },
    Gyarados: { name: "Gyarados", pokedexNumber: 130, spriteUrl: "130.png" },
    Lapras: { name: "Lapras", pokedexNumber: 131, spriteUrl: "131.png" },
    Ditto: { name: "Ditto", pokedexNumber: 132, spriteUrl: "132.png" },
    Eevee: { name: "Eevee", pokedexNumber: 133, spriteUrl: "133.png" },
    Vaporeon: { name: "Vaporeon", pokedexNumber: 134, spriteUrl: "134.png" },
    Jolteon: { name: "Jolteon", pokedexNumber: 135, spriteUrl: "135.png" },
    Flareon: { name: "Flareon", pokedexNumber: 136, spriteUrl: "136.png" },
    Porygon: { name: "Porygon", pokedexNumber: 137, spriteUrl: "137.png" },
    Omanyte: { name: "Omanyte", pokedexNumber: 138, spriteUrl: "138.png" },
    Omastar: { name: "Omastar", pokedexNumber: 139, spriteUrl: "139.png" },
    Kabuto: { name: "Kabuto", pokedexNumber: 140, spriteUrl: "140.png" },
    Kabutops: { name: "Kabutops", pokedexNumber: 141, spriteUrl: "141.png" },
    Aerodactyl: {
      name: "Aerodactyl",
      pokedexNumber: 142,
      spriteUrl: "142.png",
    },
    Snorlax: { name: "Snorlax", pokedexNumber: 143, spriteUrl: "143.png" },
    Articuno: { name: "Articuno", pokedexNumber: 144, spriteUrl: "144.png" },
    Zapdos: { name: "Zapdos", pokedexNumber: 145, spriteUrl: "145.png" },
    Moltres: { name: "Moltres", pokedexNumber: 146, spriteUrl: "146.png" },
    Dratini: { name: "Dratini", pokedexNumber: 147, spriteUrl: "147.png" },
    Dragonair: { name: "Dragonair", pokedexNumber: 148, spriteUrl: "148.png" },
    Dragonite: { name: "Dragonite", pokedexNumber: 149, spriteUrl: "149.png" },
    Mewtwo: { name: "Mewtwo", pokedexNumber: 150, spriteUrl: "150.png" },
    Mew: { name: "Mew", pokedexNumber: 151, spriteUrl: "151.png" },
  },
};
